- name: play illustrates the Slide of handlers
  hosts: somehost
  tasks:
  - name: t1
    module-a:
      attr1: val1
  - name: t2
    module-b:
      attr1: val1
    # run t3 only if t2 CHANGED 
  - name: t3
    module-c:
      attr1: val1
  - name: t4
    module-d:
      attr1: val1
