---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Hosts: where our play will run and options it will run with
  hosts: linux

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Task 1
      command: /bin/sleep 5
      when: ansible_hostname == 'centos1'
      # Wait for up to 10 seconds
      async: 10
      # When you set poll: 0, Ansible starts the task and immediately moves on to the next task without waiting for a result
      # Each async task runs until it either completes, fails or times out (runs longer than its async value). 
      # The playbook run ends without checking back on async tasks
      poll: 0

    - name: Task 2
      command: /bin/sleep 5
      when: ansible_hostname == 'centos2'
      async: 10
      poll: 0

    - name: Task 3
      command: /bin/sleep 5
      when: ansible_hostname == 'centos3'
      async: 10
      poll: 0

    - name: Task 4
      command: /bin/sleep 30
      when: ansible_hostname == 'ubuntu1'
      async: 10
      poll: 0

    - name: Task 5
      command: /bin/sleep 5
      when: ansible_hostname == 'ubuntu2'
      async: 10
      poll: 0

    - name: Task 6
      command: /bin/sleep 5
      when: ansible_hostname == 'ubuntu3'
      async: 10
      poll: 0

# Three dots indicate the end of a YAML document
...
